config/routes.rb
Rails.application.routes.draw do
  Rails.application.routes.draw do
    devise_for :users, controllers: {
      sessions: 'users/sessions'
    }
  end
  resources :items
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  get '/search_item', to: 'search#search_item'
  get '/settings', to: 'settings#index', as: :settings
  get '/locations/new', to: 'settings#new_location', as: :new_location
  get '/location', to: 'settings#new_location', as: :locations
  post '/location', to: 'settings#create_location'
  get '/cards/new', to: 'settings#new_card', as: :cards
  post '/cards/new', to: 'settings#create_card'
  post '/defaultlocation/set/:location_id', to: 'settings#make_default_location', as: :make_default_location
  get '/lease/new/:item_id', to: 'lease#new', as: :new_lease
  post '/leases', to: 'lease#create', as: :create_lease
  get '/leases', to: 'lease#index', as: :leases
  delete '/location/:id/delete', to: 'settings#delete_location', as: :delete_location
  root "items#index"
  resources :leases
end

app/controllers/settings_controller.rb
class SettingsController < ApplicationController
    def index
    end
    def new_location
        @location = Location.new
    end
    def new_card
        @card = Card.new
    end
    def create_card
        puts "params1" + card_params[:year]
        card_check = ActiveMerchant::Billing::CreditCard.new(card_params)
        puts "validate" + card_check.validate.inspect
        @card = Card.new(card_params)
        if card_params[:year].length == 2
            card_check.year.to_s.prepend('20')
            card_check.year += 2000
            @card.year.prepend('20')
        end
        @card.user_id = current_user.id
        if card_check.validate.empty?
            @card.save
        end
        puts request.referer.inspect
        respond_to do |format|
            if @card.save
                if params[:commit_type] == "from_lease"
                    format.html { redirect_to request.referer, notice: "Card was successfully added." }
                    format.json { render :index, status: :created }
                else
                    format.html { redirect_to settings_path , notice: "Card was successfully added." }
                    format.json { render :index, status: :created }
                end
            else
                format.html { render :new_card, status: :unprocessable_entity }
                format.json { render json: @location.errors, status: :unprocessable_entity }
            end
        end
    end
    def delete_location
        @location = Location.find(params[:id])
        @location.delete
        respond_to do |format|
            if @location.save
                format.html { redirect_to settings_path , notice: "Location was successfully added." }
                format.json { render :index, status: :created }
            else
                format.html { render :index, status: :unprocessable_entity }
                format.json { render json: @location.errors, status: :unprocessable_entity }
            end
        end
    end
    def create_location
        @location = Location.new(location_params)
        #if current_user.locations.length < 1
        #    current_user.default_location = @location
        #    current_user.default_location.save
        #end
        @location.user_id = current_user.id
        #if request.referer.present? && request.referer.include?('/items/new')
        #    this_url = 

        respond_to do |format|
            if @location.save
                format.html { redirect_to settings_path , notice: "Location was successfully added." }
                format.json { render :index, status: :created }
            else
                format.html { render :index, status: :unprocessable_entity }
                format.json { render json: @location.errors, status: :unprocessable_entity }
            end
        end
    end
    def make_default_location
        current_user.default_location_id = params[:location_id]
        respond_to do |format|
            if current_user.save
                format.html { redirect_to settings_path, notice: "Successfully set as default" }
                format.json { render :index, status: :created }
            else
                format.html { render :index, status: :unprocessable_entity }
                format.json { render json: @location.errors, status: :unprocessable_entity }
            end
        end
        # location = Location.find(:id)
        # user.default_location = location
    end
    private
    def location_params
        params.require(:location).permit(:id, :address, :city, :state, :location_id)
    end
    def card_params
        params.require(:card).permit(:id, :first_name, :last_name, :number, :month, :year, :verification_value)
    end
end

app/helpers/settings_helper.rb
module SettingsHelper
end

app/views/settings/index.html.erb
<%= link_to "Home", root_path %><br>
<%= link_to 'Add a location', new_location_path %>
<% current_user.locations.each do |location| %>
    <% if current_user.default_location_id != location.id %>
        <p><%= location.address %>, <%= location.city %>, <%= location.state %></p>
        <%= button_to 'Make default', make_default_location_path(location.id), method: :post %>
    <% else %>
        <h4>Default: <%= location.address %>, <%= location.city %>, <%= location.state %></h4>
    <% end %>
    <%= button_to "Delete", delete_location_path(location.id), method: :delete %>
<% end %>
<%= link_to 'Add a card', cards_path %>

<% current_user.cards.each do |card| %>
    <%= card.number %>
<% end %>

app/views/settings/new_card.html.erb
<%= link_to "Go back", :back %>
<%= form_for @card do |f| %>
    <%= f.text_field :first_name, placeholder: 'First Name' %>
    <%= f.text_field :last_name, placeholder: 'Last Name' %>
    <%= f.text_field :number, placeholder: 'Card number' %>
    <%= f.text_field :month, placeholder: 'Month' %>
    <%= f.text_field :year, placeholder: 'Year' %>
    <%= f.text_field :verification_value, placeholder: 'Verification' %>
    <%= f.submit 'Add card' %>
<% end %>

app/views/settings/new_location.html.erb
<%= link_to "Go back", :back %>
<%= form_for @location do |f| %>
    <%= f.text_field :address, placeholder: "Address" %>
    <%= f.text_field :city, placeholder: "City" %>
    <%= f.text_field :state, placeholder: "State" %>
    <%= f.submit "Add location" %>
<% end %>