config/routes.rb
Rails.application.routes.draw do
  Rails.application.routes.draw do
    devise_for :users, controllers: {
      sessions: 'users/sessions'
    }
  end
  resources :items
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  get '/search_item', to: 'search#search_item'
  get '/settings', to: 'settings#index', as: :settings
  get '/locations/new', to: 'settings#new_location', as: :new_location
  get '/location', to: 'settings#new_location', as: :locations
  post '/location', to: 'settings#create_location'
  get '/cards/new', to: 'settings#new_card', as: :cards
  post '/cards/new', to: 'settings#create_card'
  post '/defaultlocation/set/:location_id', to: 'settings#make_default_location', as: :make_default_location
  get '/lease/new/:item_id', to: 'lease#new', as: :new_lease
  post '/leases', to: 'lease#create', as: :create_lease
  get '/leases', to: 'lease#index', as: :leases
  delete '/location/:id/delete', to: 'settings#delete_location', as: :delete_location
  root "items#index"
  resources :leases
end

app/models/item.rb
class Item < ApplicationRecord
    belongs_to :user
    belongs_to :location
    has_one :lease
    def validate 
        errors.add(:price, "should be at least 0.01") if price.nil? || price < 0.01 
    end 
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: %i[ show edit update destroy ]

  # GET /items or /items.json
  def index
    @items = Item.all
    # Geocoder.search(94558).first.data["lat"].to_f -- latitude
  end

  # GET /items/1 or /items/1.json
  def show
  end
  def locations_sorted
  end
  # GET /items/new
  def new
    @item = Item.new
  end
  # GET /items/1/edit
  def edit
  end

  # POST /items or /items.json
  def create
    #@item = Item.new(item_params)
    puts "item" + params[:item].inspect
    location = Location.find(params[:item][:location_id])
    puts "location" + location.inspect
    @item = location.items.new(item_params)
    @item.user = current_user
    #@item.price = params[:price]
    #puts "hereeeee" + params[:price]
    #@item.user_id = current_user.id
    #@item.location = current_user.locations.find_by(params[:location])
    @item.save
    respond_to do |format|
      if @item.save
        format.html { redirect_to item_url(@item), notice: "Item was successfully created." }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1 or /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to item_url(@item), notice: "Item was successfully updated." }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1 or /items/1.json
  def destroy
    @item.destroy

    respond_to do |format|
      format.html { redirect_to items_url, notice: "Item was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def item_params
      params.require(:item).permit(:name, :desc, :location_id, :price)
    end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_form.html.erb
<%= form_with(model: item) do |form| %>
  <% if item.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
        <% item.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :desc, style: "display: block" %>
    <%= form.text_area :desc %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/items/_item.html.erb
<div id="<%= dom_id item %>">
  <p>
    <strong>Name:</strong>
    <%= item.name %>
  </p>

  <p>
    <strong>Desc:</strong>
    <%= item.desc %>
  </p>

</div>

app/views/items/edit.html.erb
<h1>Editing item</h1>

<%= render "form", item: @item %>

<br>

<div>
  <%= link_to "Show this item", @item %> |
  <%= link_to "Back to items", items_path %>
</div>

app/views/items/index.html.erb
<p style="color: green"><%= notice %></p>
<h1>Items</h1>
<% if user_signed_in? %>
  <%= button_to "Sign out", destroy_user_session_path, method: :delete %>
  <%= link_to "Settings", settings_path %>
  <%= link_to "My Leases", leases_path %>
<% else %>
  <%= button_to "Sign in", new_user_session_path %> 
  <%= button_to "Sign up", new_user_registration_path, method: :get %>
<% end %>
<%= form_with url: '/search_item', method: :get do |form| %>
  <%= form.text_field :name %>
  <%= form.submit "Search" %>
<% end %>
<div id="items">
  <% @items.each do |item| %>
    <%= render item %>
    <p>
      <%= link_to "Show this item", item %>
    </p>
  <% end %>
</div>
<% if user_signed_in? %>
  <%= link_to "New item", new_item_path %>
<% else %>
  <%= link_to  "New item", new_user_registration_path %>
<% end %>

app/views/items/new.html.erb
<h1>New item</h1>

<!--<%= render "form", item: @item %>-->

<%= form_for @item do |f| %>
  <div class="field">
    <!--<%= f.label :name %>-->
    <%= f.text_field :name, placeholder: "Name" %>
  </div>
  <div class="field">
    <!--<%= f.label "Description" %>-->
    <%= f.text_area :desc, placeholder: "Description" %>
  </div>
  <% if current_user.sorted_locations.length > 0 %>
    <div class="field"> 
      <%= f.select :location_id, current_user.sorted_locations.collect { |location| [location.address, location.id] } %>
    </div>
  <% end %>
  <%= link_to 'Add a location', new_location_path %>
  <div class="field">
    $<%= f.text_field :price %> per day
  </div>
  <div class="actions">
    <%= f.submit "Post to board" %>
  </div>
<% end %>

<br>

<div>
  <%= link_to "Back to items", items_path %>
</div>

app/views/items/show.html.erb
<p style="color: green"><%= notice %></p>
<% if request.referer.present? && request.referer.include?('/search_item?') %>
  <%= link_to "Back to search results", request.referer %>
<% end %>
<%= render @item %>
<p>By: <%= @item.user.first_name %> <%= @item.user.last_name %></p>
<p><%= @item.location.address %></p>
$<%= @item.price %> per day
<div>
  <% if @item.user_id == current_user.id %>
    <%= link_to "Edit this item", edit_item_path(@item) %>
    <%= button_to "Destroy this item", @item, method: :delete %>
  <% else %>
    <% if !@item.lease %>
      <%= link_to "Rent this item", new_lease_path(item_id: @item.id) %>
    <% end %>
  <% end %>
  <%= link_to "Back to items", items_path %>
</div>