config/routes.rb
Rails.application.routes.draw do
  Rails.application.routes.draw do
    devise_for :users, controllers: {
      sessions: 'users/sessions'
    }
  end
  resources :items
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  get '/search_item', to: 'search#search_item'
  get '/settings', to: 'settings#index', as: :settings
  get '/locations/new', to: 'settings#new_location', as: :new_location
  get '/location', to: 'settings#new_location', as: :locations
  post '/location', to: 'settings#create_location'
  get '/cards/new', to: 'settings#new_card', as: :cards
  post '/cards/new', to: 'settings#create_card'
  post '/defaultlocation/set/:location_id', to: 'settings#make_default_location', as: :make_default_location
  get '/lease/new/:item_id', to: 'lease#new', as: :new_lease
  post '/leases', to: 'lease#create', as: :create_lease
  get '/leases', to: 'lease#index', as: :leases
  delete '/location/:id/delete', to: 'settings#delete_location', as: :delete_location
  root "items#index"
  resources :leases
end

app/models/lease.rb
class Lease < ApplicationRecord
    belongs_to :lessee
    belongs_to :lessor
    belongs_to :item
end

app/controllers/lease_controller.rb
class LeaseController < ApplicationController
    #before_action :create, :index
    def index
        
    end
    def new
        @lease = Lease.new
        @lease.item_id = params[:item_id]
        @item = Item.find(params[:item_id])
        @lease.save
    end
    def create
        #token = Stripe::Token.create({
        #    card: {
        #        number: '4242424242424242',
        #        exp_month: '5',
        #        exp_year: '2024',
        #        cvc: '314',
        #    },
        #})
        @lease = Lease.new(lease_params)
        puts "try" + lease_params.inspect
        @lease.id = Lease.all.length
        @item = Item.find(@lease.item_id)
        #@lease.item_id = @item.id
        @lease.save
        puts "hhehehe" + @lease.inspect
        @lessee = Lessee.new
        @lessee.user_id = current_user.id
        @lessee.lease = @lease
        @lessee.save
        puts "here" + @lessee.inspect
        @lessor = Lessor.new
        @lessor.user_id = @item.user_id
        @lessor.lease = @lease
        @lessor.save
        @lease.lessee_id = @lessee.id
        @lease.lessor_id = @lessor.id
        @lease.price = @item.price
        puts "tjere" + @lessor.inspect
        customer = Stripe::Customer.create({
            email: current_user.email,
            source: 'tok_visa',
        })
            
        charge = Stripe::Charge.create({
            :customer => customer.id,
            :amount => (@lease.item.price * 100).to_i * @lease.duration_days,
            :description => 'Description of your product',
            :currency => 'usd'
        })

        respond_to do |format|
            if @lease.save
                format.html { redirect_to root_path, notice: "Successfully rented." }
                format.json { render :index, status: :created }
            else
                format.html { render :index, status: :unprocessable_entity }
                format.json { render json: @item.errors, status: :unprocessable_entity }
            end
        end
    end
    private
    def lease_params
        params.require(:lease).permit(:price, :duration_days, :all_at_once, :item_id)
    end
end

app/helpers/lease_helper.rb
module LeaseHelper
end

app/views/lease/index.html.erb
<%= link_to "Back home", root_path %><br>
<% if current_user.lessors.length > 0 %>
    Renting out:
    <% current_user.lessors.each do |lessor| %>
        <%= lessor.lease.item.name %>
        $<%= lessor.lease.price %> per day
    <% end %>
<% end %><br>
<% if current_user.lessees.length > 0 %>
    Renting in:
    <% current_user.lessees.each do |lessee| %>
        <%= lessee.lease.item.name %>,
        $<%= lessee.lease.price %> per day,
        for <%= lessee.lease.duration_days %> days,
        <% if lessee.lease.all_at_once %>
            Paid all at once
        <% else %>
            Paid incrementally
        <% end %>
            

    <% end %>
<% end %>

<% if current_user.lessees.length + current_user.lessors.length == 0 %>
    No leases yet!
<% end %>

app/views/lease/new.html.erb
<%= @item.name %>
<%= @item.price %>
<%= form_for @lease do |f| %>
    How long do you want to rent this out for?<br>
    <%= f.text_field :duration_days %><br>
    <!--Check if you would like to pay all at once
    <%= f.check_box :all_at_once %><br>-->
    <%= f.hidden_field :item_id, value: @item.id %>
    <%= f.submit 'Rent!' %>
<% end %>
<%= link_to "Go back", item_path(@item.id) %>
<%= form_for Card.new do |f| %>
    <%= f.text_field :first_name, placeholder: "First name" %>
    <%= f.text_field :last_name, placeholder: "Last name" %>
    <%= f.text_field :number, placeholder: "Card number" %>
    <%= f.text_field :month, placeholder: "Month" %>
    <%= f.text_field :year, placeholder: "Year" %>
    <%= f.text_field :verification_value, placeholder: "CVC code" %>
    <%= f.button 'Add card', type: :submit, formmethod: :post, action: '/cards/new', name: 'commit_type', value: 'from_lease' %>
<% end %>